"""DMG installer build.

Produces app/dist/BelkaTunnel-<version>.dmg with:
  - The voxel "tunnel between two trees" background image (1x + 2x retina)
  - BelkaTunnel.app on the left tree
  - /Applications symlink on the right tree
  - 800×448 window, hidden chrome (no toolbar/sidebar/status bar)

Driven by `dmgbuild`, which renders the layout via Finder under the hood —
no manual AppleScript, deterministic result.
"""

from __future__ import annotations

import shutil
import tempfile
import tomllib
from pathlib import Path

from . import util


# Window + icon layout. Centers each icon over the corresponding tree on the
# background image. Tweak only if the background changes.
WINDOW_SIZE = (800, 448)
APP_ICON_POS = (200, 240)
APPLICATIONS_ICON_POS = (600, 240)
ICON_SIZE = 128
TEXT_SIZE = 14


def cargo_version() -> str:
    cargo = tomllib.loads((util.APP_DIR / "Cargo.toml").read_text())
    return cargo["package"]["version"]


def build_dmg() -> Path:
    """Build app/dist/BelkaTunnel-<version>.dmg from the bundled .app."""
    bundle = util.BUNDLE
    if not bundle.exists():
        util.fail(f"missing {bundle} — run `bt bundle` first")
        raise SystemExit(1)

    bg = util.APP_DIR / "assets" / "dmg-background.png"
    if not bg.exists():
        util.fail(f"missing background at {bg}")
        raise SystemExit(1)

    version = cargo_version()
    # dmgbuild always appends `.dmg` to its output filename. We build there
    # and then rename to the requested `.img` extension.
    intermediate = bundle.parent / f"BelkaTunnel-{version}.dmg"
    out = bundle.parent / f"BelkaTunnel-{version}.img"
    for p in (intermediate, out):
        if p.exists():
            p.unlink()
    util.step(f"building installer → {out.name}")

    # dmgbuild reads a Python "settings file" with module-level assignments.
    # We generate one in a temp dir so the build is reproducible from CI without
    # checking generated artifacts in.
    settings_src = f'''\
# Auto-generated by tools/bt/dmg.py — do not edit by hand.

application = {str(bundle)!r}
appname = "BelkaTunnel.app"

# Volume contents
files = [application]
symlinks = {{"Applications": "/Applications"}}
hide_extension = [appname]

# Look + feel
format = "UDZO"        # compressed
filesystem = "HFS+"
size = "300M"

background = {str(bg)!r}
window_rect = ((100, 100), {WINDOW_SIZE!r})
icon_size = {ICON_SIZE}
text_size = {TEXT_SIZE}
icon_locations = {{
    appname:        {APP_ICON_POS!r},
    "Applications": {APPLICATIONS_ICON_POS!r},
}}

default_view = "icon-view"
show_status_bar = False
show_tab_view = False
show_toolbar = False
show_pathbar = False
show_sidebar = False
show_icon_preview = False
arrange_by = None
'''

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False, encoding="utf-8"
    ) as f:
        f.write(settings_src)
        settings_path = Path(f.name)

    try:
        import dmgbuild

        dmgbuild.build_dmg(
            filename=str(intermediate),
            volume_name="БелкаТуннель",
            settings_file=str(settings_path),
        )
    finally:
        settings_path.unlink(missing_ok=True)

    intermediate.rename(out)
    size_mb = out.stat().st_size / 1024 / 1024
    util.ok(f"installer ready: {out} ({size_mb:.1f} MB)")
    return out


def verify_dmg() -> None:
    """Sanity-check the latest produced DMG can be mounted and contains the app."""
    util.step("verify DMG")
    version = cargo_version()
    dmg = util.BUNDLE.parent / f"BelkaTunnel-{version}.img"
    if not dmg.exists():
        util.fail(f"missing {dmg} — run `bt dmg` first")
        raise SystemExit(1)

    # Mount, verify contents, detach
    r = util.run(
        [
            "hdiutil",
            "attach",
            "-nobrowse",
            "-readonly",
            "-noverify",
            "-plist",
            str(dmg),
        ],
        capture=True,
    )
    import plistlib

    info = plistlib.loads(r.stdout.encode("utf-8"))
    mount_point: str | None = None
    for ent in info.get("system-entities", []):
        mp = ent.get("mount-point")
        if mp:
            mount_point = mp
            break
    if not mount_point:
        util.fail("could not find mount-point in hdiutil output")
        raise SystemExit(1)
    util.ok(f"mounted at {mount_point}")

    try:
        app_in_dmg = Path(mount_point) / "BelkaTunnel.app"
        if not app_in_dmg.exists():
            util.fail("BelkaTunnel.app missing inside DMG")
            raise SystemExit(1)
        util.ok("BelkaTunnel.app present")
        apps_link = Path(mount_point) / "Applications"
        if not apps_link.is_symlink():
            util.fail("/Applications symlink missing")
            raise SystemExit(1)
        if str(apps_link.readlink()) != "/Applications":
            util.fail(f"/Applications symlink points to {apps_link.readlink()}")
            raise SystemExit(1)
        util.ok("/Applications symlink valid")
    finally:
        util.run(
            ["hdiutil", "detach", "-quiet", "-force", mount_point], check=False
        )

    util.ok("DMG verification passed")
