"""DMG installer build.

Produces app/dist/BelkaTunnel-<version>.dmg with:
  - The voxel "tunnel between two trees" background image (1x + 2x retina)
  - BelkaTunnel.app on the left tree
  - /Applications symlink on the right tree
  - 800×448 window, hidden chrome (no toolbar/sidebar/status bar)

Driven by `dmgbuild`, which renders the layout via Finder under the hood —
no manual AppleScript, deterministic result.
"""

from __future__ import annotations

import shutil
import tempfile
import tomllib
from pathlib import Path

from . import util


# Window + icon layout. Centers each icon over the corresponding tree on the
# background image. Tweak only if the background changes.
WINDOW_SIZE = (800, 448)
APP_ICON_POS = (200, 240)
APPLICATIONS_ICON_POS = (600, 240)
ICON_SIZE = 128
# Finder's overlay label text. The visible labels ("BelkaTunnel.app",
# "Applications") are BAKED INTO the background PNG as white text at
# the right positions. Finder still draws its own overlay text on top —
# we set text_size to the smallest Finder will honour so that overlay
# barely shows. Combined with the dark gradient at the bottom of the
# bg, the painted-in white labels are what the user actually reads.
TEXT_SIZE = 8


def cargo_version() -> str:
    cargo = tomllib.loads((util.APP_DIR / "Cargo.toml").read_text())
    return cargo["package"]["version"]


def build_dmg() -> Path:
    """Build app/dist/BelkaTunnel-<version>.dmg from the bundled .app."""
    bundle = util.BUNDLE
    if not bundle.exists():
        util.fail(f"missing {bundle} — run `bt bundle` first")
        raise SystemExit(1)

    bg = util.APP_DIR / "assets" / "dmg-background.png"
    if not bg.exists():
        util.fail(f"missing background at {bg}")
        raise SystemExit(1)
    # The .dmg file's Finder icon is intentionally DIFFERENT from the .app
    # bundle's icon — the .app uses the official BelkaTunnel design,
    # the .dmg file uses the papal-purple БТ mark generated by
    # tools/make_app_icon.py. Falls back to AppIcon.icns if DmgIcon.icns
    # is absent (e.g. a fresh checkout without the generated file).
    icon = util.APP_DIR / "assets" / "DmgIcon.icns"
    if not icon.exists():
        icon = util.APP_DIR / "assets" / "AppIcon.icns"
    if not icon.exists():
        util.fail(f"missing icon at {icon}")
        raise SystemExit(1)

    version = cargo_version()
    out = bundle.parent / f"BelkaTunnel-{version}.dmg"
    if out.exists():
        out.unlink()
    util.step(f"building installer → {out.name}")

    # dmgbuild reads a Python "settings file" with module-level assignments.
    # We generate one in a temp dir so the build is reproducible from CI without
    # checking generated artifacts in.
    #
    # `icon` sets the .dmg file's Finder icon (otherwise the default generic
    # disk-image icon shows). We reuse the .app bundle's own AppIcon.icns so
    # there's only one source of brand art.
    settings_src = f'''\
# Auto-generated by tools/bt/dmg.py — do not edit by hand.

application = {str(bundle)!r}
appname = "BelkaTunnel.app"

# Volume contents
files = [application]
symlinks = {{"Applications": "/Applications"}}
hide_extension = [appname]

# Look + feel
format = "UDZO"        # compressed
filesystem = "HFS+"
size = "300M"

icon = {str(icon)!r}
background = {str(bg)!r}
window_rect = ((100, 100), {WINDOW_SIZE!r})
icon_size = {ICON_SIZE}
text_size = {TEXT_SIZE}
icon_locations = {{
    appname:        {APP_ICON_POS!r},
    "Applications": {APPLICATIONS_ICON_POS!r},
}}

default_view = "icon-view"
show_status_bar = False
show_tab_view = False
show_toolbar = False
show_pathbar = False
show_sidebar = False
show_icon_preview = False
arrange_by = None
'''

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False, encoding="utf-8"
    ) as f:
        f.write(settings_src)
        settings_path = Path(f.name)

    try:
        import dmgbuild

        dmgbuild.build_dmg(
            filename=str(out),
            volume_name="БелкаТуннель",
            settings_file=str(settings_path),
        )
    finally:
        settings_path.unlink(missing_ok=True)

    _set_file_icon(out, icon)
    size_mb = out.stat().st_size / 1024 / 1024
    util.ok(f"installer ready: {out} ({size_mb:.1f} MB)")
    return out


def _set_file_icon(target: Path, icon_path: Path) -> None:
    """Set the macOS Finder icon on `target` from an .icns file.

    dmgbuild's own `icon = ...` setting silently no-ops in our environment
    (the resource fork stays empty), so we set it directly via NSWorkspace.
    Confirmed via `xattr -l <dmg>` showing com.apple.ResourceFork after this
    call but not before.
    """
    try:
        from AppKit import NSImage, NSWorkspace
    except ImportError:
        util.warn(
            "PyObjC not available; DMG file icon not set "
            "(`uv add pyobjc` in tools/)"
        )
        return
    img = NSImage.alloc().initWithContentsOfFile_(str(icon_path))
    ok = NSWorkspace.sharedWorkspace().setIcon_forFile_options_(
        img, str(target), 0
    )
    if not ok:
        util.warn(f"NSWorkspace.setIcon returned False for {target}")


def pfusers_cargo_version() -> str:
    cargo = tomllib.loads((util.REPO_ROOT / "pfusers" / "Cargo.toml").read_text())
    return cargo["package"]["version"]


def build_pfusers_dmg() -> Path:
    """Build pfusers/dist/pfUsers-<version>.dmg from the bundled .app.

    Mirrors build_dmg() but for the pfUsers admin app. No custom background
    image (pfUsers doesn't ship one); dmgbuild renders the default Finder
    look — still clean, still drag-to-Applications. If a custom backdrop
    materialises later, drop it at pfusers/assets/dmg-background.png and
    add the `background = …` line.
    """
    from .build import PFUSERS_BUNDLE, PFUSERS_DIR

    bundle = PFUSERS_BUNDLE
    if not bundle.exists():
        util.fail(f"missing {bundle} — run `bt bundle-pfusers` first")
        raise SystemExit(1)

    version = pfusers_cargo_version()
    out = bundle.parent / f"pfUsers-{version}.dmg"
    if out.exists():
        out.unlink()
    util.step(f"building installer → {out.name}")

    # Reuse the БелкаТуннель papal-purple БТ DmgIcon (NOT the .app icon)
    # for the pfUsers DMG file icon. Better than the default generic
    # disk-image icon; visually consistent with the BelkaTunnel DMG.
    icon_path = util.APP_DIR / "assets" / "DmgIcon.icns"
    if not icon_path.exists():
        icon_path = util.APP_DIR / "assets" / "AppIcon.icns"
    icon_line = (
        f"icon = {str(icon_path)!r}" if icon_path.exists() else "# (no icon)"
    )
    settings_src = f'''\
# Auto-generated by tools/bt/dmg.py — do not edit by hand.

application = {str(bundle)!r}
appname = "pfUsers.app"

{icon_line}

files = [application]
symlinks = {{"Applications": "/Applications"}}
hide_extension = [appname]

format = "UDZO"
filesystem = "HFS+"
size = "300M"

window_rect = ((100, 100), {WINDOW_SIZE!r})
icon_size = {ICON_SIZE}
text_size = {TEXT_SIZE}
icon_locations = {{
    appname:        {APP_ICON_POS!r},
    "Applications": {APPLICATIONS_ICON_POS!r},
}}

default_view = "icon-view"
show_status_bar = False
show_tab_view = False
show_toolbar = False
show_pathbar = False
show_sidebar = False
show_icon_preview = False
arrange_by = None
'''

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False, encoding="utf-8"
    ) as f:
        f.write(settings_src)
        settings_path = Path(f.name)

    try:
        import dmgbuild

        dmgbuild.build_dmg(
            filename=str(out),
            volume_name="pfUsers",
            settings_file=str(settings_path),
        )
    finally:
        settings_path.unlink(missing_ok=True)
    _ = PFUSERS_DIR  # silence unused; useful when we add asset paths later

    if icon_path.exists():
        _set_file_icon(out, icon_path)
    size_mb = out.stat().st_size / 1024 / 1024
    util.ok(f"installer ready: {out} ({size_mb:.1f} MB)")
    return out


def verify_pfusers_dmg() -> None:
    """Mount the latest pfUsers DMG, verify contents, detach."""
    from .build import PFUSERS_BUNDLE

    util.step("verify pfUsers DMG")
    version = pfusers_cargo_version()
    dmg = PFUSERS_BUNDLE.parent / f"pfUsers-{version}.dmg"
    if not dmg.exists():
        util.fail(f"missing {dmg} — run `bt dmg-pfusers` first")
        raise SystemExit(1)

    r = util.run(
        [
            "hdiutil",
            "attach",
            "-nobrowse",
            "-readonly",
            "-noverify",
            "-plist",
            str(dmg),
        ],
        capture=True,
    )
    import plistlib

    info = plistlib.loads(r.stdout.encode("utf-8"))
    mount_point: str | None = None
    for ent in info.get("system-entities", []):
        mp = ent.get("mount-point")
        if mp:
            mount_point = mp
            break
    if not mount_point:
        util.fail("could not find mount-point in hdiutil output")
        raise SystemExit(1)
    util.ok(f"mounted at {mount_point}")
    try:
        app_in_dmg = Path(mount_point) / "pfUsers.app"
        if not app_in_dmg.exists():
            util.fail("pfUsers.app missing inside DMG")
            raise SystemExit(1)
        util.ok("pfUsers.app present")
        apps_link = Path(mount_point) / "Applications"
        if not apps_link.is_symlink():
            util.fail("/Applications symlink missing")
            raise SystemExit(1)
        util.ok("/Applications symlink valid")
    finally:
        util.run(
            ["hdiutil", "detach", "-quiet", "-force", mount_point], check=False
        )
    util.ok("pfUsers DMG verification passed")


def verify_dmg() -> None:
    """Sanity-check the latest produced DMG can be mounted and contains the app."""
    util.step("verify DMG")
    version = cargo_version()
    dmg = util.BUNDLE.parent / f"BelkaTunnel-{version}.dmg"
    if not dmg.exists():
        util.fail(f"missing {dmg} — run `bt dmg` first")
        raise SystemExit(1)

    # Mount, verify contents, detach
    r = util.run(
        [
            "hdiutil",
            "attach",
            "-nobrowse",
            "-readonly",
            "-noverify",
            "-plist",
            str(dmg),
        ],
        capture=True,
    )
    import plistlib

    info = plistlib.loads(r.stdout.encode("utf-8"))
    mount_point: str | None = None
    for ent in info.get("system-entities", []):
        mp = ent.get("mount-point")
        if mp:
            mount_point = mp
            break
    if not mount_point:
        util.fail("could not find mount-point in hdiutil output")
        raise SystemExit(1)
    util.ok(f"mounted at {mount_point}")

    try:
        app_in_dmg = Path(mount_point) / "BelkaTunnel.app"
        if not app_in_dmg.exists():
            util.fail("BelkaTunnel.app missing inside DMG")
            raise SystemExit(1)
        util.ok("BelkaTunnel.app present")
        apps_link = Path(mount_point) / "Applications"
        if not apps_link.is_symlink():
            util.fail("/Applications symlink missing")
            raise SystemExit(1)
        if str(apps_link.readlink()) != "/Applications":
            util.fail(f"/Applications symlink points to {apps_link.readlink()}")
            raise SystemExit(1)
        util.ok("/Applications symlink valid")
    finally:
        util.run(
            ["hdiutil", "detach", "-quiet", "-force", mount_point], check=False
        )

    util.ok("DMG verification passed")
